Repository jt-owo/tune, pull requests merged in 2023-04, with the labels that each got.

#26 22 add queue item container to queue drag and drop hide
  src/ui/components/AudioPlayer/SeekBar/SeekBar.tsx
  src/ui/components/Queue/Queue.module.scss
  src/ui/components/Queue/Queue.tsx
  src/ui/components/Queue/QueueTrack/QueueTrack.tsx
  src/ui/views/Playlist/Playlist.tsx
Labels: bug

#27 Update modules
  .husky/pre-commit
  SCRIPTS.md
  SETUP.md
  package-lock.json
  package.json
  release/app/package-lock.json
  release/app/package.json
  src/main/api/discordClient.ts
  src/main/main.ts
  src/ui/views/Playlist/Playlist.tsx
  webpack/configs/webpack.config.base.ts
  webpack/configs/webpack.config.main.prod.ts
  webpack/configs/webpack.config.preload.dev.ts
  webpack/configs/webpack.config.renderer.dev.dll.ts
  webpack/configs/webpack.config.renderer.dev.ts
  webpack/configs/webpack.config.renderer.prod.ts
  webpack/configs/webpack.paths.ts
  webpack/scripts/checkNodeEnv.js
  webpack/scripts/checkPort.js
  webpack/scripts/clean.js
  webpack/scripts/cleanBuildFiles.js
  webpack/scripts/deleteSourceMaps.js
  webpack/scripts/electronRebuild.js
  webpack/scripts/notarize.js
  webpack/scripts/util.js
Labels: enhancement

#28 Fix line breaks in SETUP.md
  SETUP.md
Labels: bug

#29 Add '.ejs' files to .gitattributes
  .gitattributes
Labels: enhancement

#31 Add Spotify playlists
  .eslintrc.js
  src/main/api/database.ts
  src/main/api/discordClient.ts
  src/state/slices/playerSlice.ts
  src/state/slices/playlistSlice.ts
  src/state/store.ts
  src/typings/metadata.ts
  src/typings/spotify/general.ts
  src/typings/spotify/items.ts
  src/typings/spotify/results.ts
  src/typings/spotifyAPI/index.ts
  src/typings/types.ts
  src/ui/Application.tsx
  src/ui/api/spotify/index.ts
  src/ui/api/spotify/parser.ts
  src/ui/components/AudioPlayer/AudioPlayer.tsx
  src/ui/components/ContextMenu/ContextMenuExample.tsx
  src/ui/components/Home_Elements/HomeItemSmall/HomeItemSmall.tsx
  src/ui/components/Navigation/Navigation.tsx
  src/ui/components/Queue/QueueTrack/QueueTrack.tsx
  src/ui/routes.ts
  src/ui/util/formatHelper.ts
  src/ui/util/serviceHelper.ts
  src/ui/util/spotifyParser.ts
  src/ui/views/Browse/Browse.tsx
  src/ui/views/Home/Home.tsx
  src/ui/views/Library/Library.tsx
  src/ui/views/Playlist/Playlist.tsx
  src/ui/views/Playlist/PlaylistTrack/PlaylistTrack.tsx
  src/ui/views/Settings/Settings.tsx
Labels: enhancement

#37 Optimization
  src/main/main.ts
  src/main/window/window.ts
  src/state/slices/playerSlice.ts
  src/state/slices/playlistsSlice.ts
  src/ui/components/AudioPlayer/AudioPlayer.tsx
  src/ui/components/AudioPlayer/NowPlaying/NowPlaying.tsx
  src/ui/components/ContextMenu/ContextMenu.tsx
  src/ui/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
  src/ui/components/HamburgerMenu/HamburgerMenuItem/HamburgerMenuItem.tsx
  src/ui/components/Queue/Queue.tsx
  src/ui/util/index.ts
  src/ui/views/Playlist/Playlist.tsx
  src/ui/views/Playlist/PlaylistTrack/PlaylistTrack.tsx
Labels: enhancement

#38 Fix bad setState call in Playlist component
  src/ui/views/Playlist/Playlist.tsx
Labels: enhancement

#39 Add CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement

#40 Update workflows to run only when necessary
  .github/workflows/package.yml
  .github/workflows/tests.yml
Labels: enhancement

#41 Fix workflow syntax error
  .github/workflows/package.yml
  .github/workflows/tests.yml
  src/main/main.ts
Labels: bug, enhancement

#44 Add workflow to run tests & packaging automatically
  .github/workflows/packaging.yml
  .github/workflows/tests.yml
  src/ui/Application.tsx
Labels: enhancement

#45 Feature
  assets/animations/checkmark-green.json
  assets/ui-icons/add-bottom.svg
  assets/ui-icons/add-top.svg
  assets/ui-icons/image-regular.svg
  assets/ui-icons/shuffle-svgrepo-com.svg
  assets/ui-icons/simple-play-btn.svg
  assets/ui-icons/three-dots.svg
  assets/ui-icons/x-mark.svg
  src/ui/Application.scss
  src/ui/components/DropdownMenu/DropdownMenu.module.scss
  src/ui/components/DropdownMenu/DropdownMenu.tsx
  src/ui/components/DropdownMenu/DropdownMenuItem/DropdownMenuItem.module.scss
  src/ui/components/DropdownMenu/DropdownMenuItem/DropdownMenuItem.tsx
  src/ui/components/Home_Elements/HomeItemMedium/HomeItemMedium.module.scss
  src/ui/components/Queue/Queue.module.scss
  src/ui/components/Queue/Queue.tsx
  src/ui/styles/_animations.scss
  src/ui/views/Home/Home.module.scss
  src/ui/views/Home/Home.tsx
  src/ui/views/Playlist/Playlist.module.scss
  src/ui/views/Settings/Settings.module.scss
  src/ui/views/Settings/Settings.tsx
Labels: enhancement

#48 Switch from electron to castLabs ECS for widevine support
  package-lock.json
  package.json
  src/main/main.ts
  src/ui/views/Settings/Settings.tsx
Labels: enhancement

#49 Add Feature request template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#50 Playlist Rework
  assets/animations/bookmark.json
  assets/service-icons/Spotify_Icon_RGB_Green.png
  assets/ui-icons/add-bottom.svg
  assets/ui-icons/add-top.svg
  assets/ui-icons/file-plus.svg
  assets/ui-icons/hard-drive.svg
  assets/ui-icons/help-circle.svg
  assets/ui-icons/play-solid.svg
  assets/ui-icons/three-dots.svg
  assets/ui-icons/trash-2.svg
  src/main/window/window.ts
  src/typings/types.ts
  src/ui/components/AudioPlayer/SeekBar/SeekBar.tsx
  src/ui/components/ContextMenu/ContextMenu.module.scss
  src/ui/components/ContextMenu/ContextMenuItem/ContextMenuItem.module.scss
  src/ui/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
  src/ui/components/Navigation/Navigation.module.scss
  src/ui/components/Navigation/Navigation.tsx
  src/ui/components/Queue/Queue.module.scss
  src/ui/components/RenameDialog/RenameDialog.tsx
  src/ui/components/ToolTip/ToolTip.module.scss
  src/ui/components/View/View.module.scss
  src/ui/hooks/useContextMenu.ts
  src/ui/hooks/useLottie.ts
  src/ui/styles/_animations.scss
  src/ui/styles/_colors.scss
  src/ui/util/format.ts
  src/ui/views/Playlist/Playlist.module.scss
  src/ui/views/Playlist/Playlist.tsx
  src/ui/views/Playlist/PlaylistHeader/PlaylistHeader.tsx
  src/ui/views/Playlist/PlaylistTrack/PlaylistTrack.tsx
Labels: enhancement, bugfix

#51 Update Spotify Types & Discord RPC
  src/main/api/discordClient.ts
  src/main/ipc/channel.ts
  src/main/main.ts
  src/main/preload.ts
  src/typings/preload.d.ts
  src/typings/spotify/general.ts
  src/typings/spotify/items.ts
  src/typings/spotify/results.ts
  src/typings/types.ts
  src/ui/api/spotify/index.ts
  src/ui/api/spotify/parser.ts
  src/ui/api/spotify/spotify.d.ts
  src/ui/components/AudioPlayer/NowPlaying/NowPlaying.tsx
Labels: enhancement
